cvProject_2/Models/_Task.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
namespace cvProject_2.Models;

public class _Task
{
    public enum status{
        ToDo = 1,
        InProgress = 2,
        Done = 3
    }
    [Key]
    public int Id {get; set;}
    [Required]
    public string Name{get;set;} = string.Empty;
    [Required]
    
    public string Description{get; set;}= string.Empty;
    [Range(1,3, ErrorMessage="Enter as an integer: 1 - ToDo, 2 - InProgress, 3 - Done")]
    public status Status{get;set;}= status.ToDo;
    [Range(0, 100,ErrorMessage = "Priority must be from 0 (low) to 100 (high)")]
    public int Priority{get; set;}
    [Required]
    public int ProjectId{get;set;}
        // public List<Task> Tasks {get; set;}
}

cvProject_2/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using cvProject_2.Models;
using cvProject_2.Data;

namespace cvProject_2.Controllers;

public class ProjectController : Controller
{

    private readonly ApplicationDbContext _context;
    public ProjectController(ApplicationDbContext context)
    {
        _context=context;
    }
    //GET
    //Lists all projects
    public IActionResult Index()
    {
        IEnumerable<Project> projects = _context.myProjects;
        return View(projects);
    }
    //GET 
    //Creates a project
    public IActionResult Create()
    {
        return View();
    }
    //POST
    //Send post query
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Project proj)
    {
        if(proj.EndDate < proj.StartDate){
            ModelState.AddModelError("startdate", "The end date of project must be after the starting date");
        }
        if(ModelState.IsValid){
            _context.myProjects.Add(proj);
            _context.SaveChanges();
            TempData["success"]="Project created successfully";
            return RedirectToAction("Index");
        }
        return View(proj);
    }
    //GET
    //Edit a project
    public IActionResult Edit(int? id)
    {
        if(id == null||id==0){
            return NotFound();
        }
        var proj = _context.myProjects.Find(id);
        if(proj==null){
            return NotFound();
        }
        return View(proj);
    }
    //POST
    //Send update query
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Project proj)
    {
        if(proj.EndDate < proj.StartDate){
            ModelState.AddModelError("startdate", "The end date of project must be after the starting date");
        }
        if(ModelState.IsValid){
            _context.myProjects.Update(proj);
            _context.SaveChanges();
            TempData["success"]="Project updated successfully";
            return RedirectToAction("Index");
        }
        return View(proj);
    }
    //GET
    //Delete a project
    public IActionResult Delete(int? id)
    {
        if(id == null||id==0){
            return NotFound();
        }
        var proj = _context.myProjects.Find(id);
        if(proj==null){
            return NotFound();
        }
        return View(proj);
    }

    //POST
    //Send remove query
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(Project proj)
    {
        var toDelete = _context.myProjects.Find(proj.Id);
        if(toDelete==null){
            return NotFound();
        }
        foreach(_Task task in _context.myTasks){
            if(task.ProjectId == proj.Id){
                _context.myTasks.Remove(task);
            }
        }
        _context.myProjects.Remove(toDelete);
        _context.SaveChanges();
        TempData["success"]="Project deleted successfully";
        return RedirectToAction("Index");
    }
    

}

cvProject_2/Controllers/TaskController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using cvProject_2.Models;
using cvProject_2.Data;

namespace cvProject_2.Controllers;

public class TaskController : Controller
{
    private readonly ApplicationDbContext _context;
    public TaskController(ApplicationDbContext context)
    {
        _context=context;
    }
    //GET
    //List all tasks of the project given by id
    public IActionResult Index(int? id)
    {
        if(id == null){
            return NotFound();
        }
        var proj = _context.myProjects.Find(id);
        if(proj==null){
            return NotFound();
        }
        ViewModel_List model = new ViewModel_List();
        model.Proj = proj;
        model.Tasks =_context.myTasks.ToList();
        return View(model);
    }
    //GET
    //Creates a task for project given by its id
    public IActionResult Create(int? id)
    {
        return View();
    }
    //POST
    //Sends post query to post a task
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(_Task task)
    {
        if(ModelState.IsValid){
            task.Id = 0;
            _context.myTasks.Add(task);
            _context.SaveChanges();
            TempData["success"]="Project created successfully";
            return RedirectToAction("Index", new {id =task.ProjectId});
        }
        return View(task.ProjectId);
    }
    //GET
    //Edits a task given by tasks id
    public IActionResult Edit(int? id)
    {
        if(id == null||id==0){
            return NotFound();
        }
        var task = _context.myTasks.Find(id);
        if(task==null){
            return NotFound();
        }
        return View(task);
    }
    //POST
    //Sends update query
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(_Task task)
    {
        if(ModelState.IsValid){
            _context.myTasks.Update(task);
            _context.SaveChanges();
            TempData["success"]="Project updated successfully";
            return RedirectToAction("Index", new {id =task.ProjectId});
        }
        return View(task);
    }
    //GET
    //Deletes a task given by task id
    public IActionResult Delete(int? id)
    {
        if(id == null||id==0){
            return NotFound();
        }
        var task = _context.myTasks.Find(id);
        if(task==null){
            return NotFound();
        }
        return View(task);
    }
    //POST
    //Send a remove query
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(_Task task)
    {
        var toDelete = _context.myTasks.Find(task.Id);
        if(toDelete==null){
            return NotFound();
        }
        _context.myTasks.Remove(toDelete);
        _context.SaveChanges();
        TempData["success"]="Project deleted successfully";
        return RedirectToAction("Index", new {id =task.ProjectId});
    }
    

}

cvProject_2/Views/Task/Create.cshtml
@model _Task
@{
    ViewData["Title"] = "Add Task";
}

<form method="post">
    <input asp-for="ProjectId" type="hidden" value='@Url.ActionContext.RouteData.Values["id"]' />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Status"></label>
            <input asp-for="Status" class="form-control" placeholder="1 - ToDo, 2 - InProgress, 3 - Done" />
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label>
            <input asp-for="Priority" class="form-control" placeholder="from 1 (min) to 100 (max)" />
            <span asp-validation-for="Priority" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create Task</button>
        <a asp-controller="Task" asp-action="Index" asp-route-id='@Url.ActionContext.RouteData.Values["id"]'
            class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts
{
@{
    <partial name="_ValidationScriptsPartial" />
}
}

cvProject_2/Views/Task/Delete.cshtml
@model _Task
@{
    ViewData["Title"] = "Delete Task";
}

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <input asp-for="ProjectId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Status"></label>
            <input asp-for="Status" disabled class="form-control" placeholder="1 - ToDo, 2 - InProgress, 3 - Done" />
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label>
            <input asp-for="Priority" disabled class="form-control" placeholder="from 1 (min) to 100 (max)" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Task" asp-action="Index" asp-route-id="@Model.ProjectId" class="btn btn-secondary"
            style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts
{
@{
    <partial name="_ValidationScriptsPartial" />
}
}

cvProject_2/Views/Task/Edit.cshtml
@model _Task
@{
    ViewData["Title"] = "Edit Task";
}

<form method="post">
    <input asp-for="ProjectId" hidden />
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Status"></label>
            <input asp-for="Status" class="form-control" placeholder="1 - ToDo, 2 - InProgress, 3 - Done" />
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label>
            <input asp-for="Priority" class="form-control" placeholder="from 1 (min) to 100 (max)" />
            <span asp-validation-for="Priority" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Edit Task</button>
        <a asp-controller="Task" asp-action="Index" asp-route-id="@Model.ProjectId" class="btn btn-secondary"
            style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts
{
@{
    <partial name="_ValidationScriptsPartial" />
}
}

cvProject_2/Views/Task/Index.cshtml
@model ViewModel_List
@{
    ViewData["Title"] = "List Tasks";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">The list of tasks for project @Model.Proj.Name</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Task" asp-action="Create" asp-route-id="@Model.Proj.Id" class="btn btn-primary">
                Create new Task
            </a>
        </div>
    </div>
    <br /><br />


    <table class="table table-bordered table-stripped" style="width:100%">
        <thead>
            <tr>
                <th>
                    The task
                </th>
                <th>
                    Description
                </th>
                <th>
                    Status
                </th>
                <th>
                    Priority
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var task in Model.Tasks)
            {
                @if (task.ProjectId != Model.Proj.Id)
                {
                    continue;
                }
                <tr>
                    <td width="15%">
                        @task.Name
                    </td>
                    <td width="20%">
                        @task.Description
                    </td>
                    <td width="20%">
                        @task.Status
                    </td>
                    <td width="10%">
                        @task.Priority
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Task" asp-action="Edit" asp-route-id="@task.Id"
                            class="btn btn-primary mx-2">Edit</a>
                            <a asp-controller="Task" asp-action="Delete" asp-route-id="@task.Id"
                            class="btn btn-danger mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-controller="Project" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Back to Projects
    </a>
</div>